version: '3'
services:
  web:
    build: .
    ports: 
      - "3000:3000"
  mongodb:
    image: mongo
    ports:
      -"27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
  nginx:
    image: nginx
    ports:
      -"80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web